name: Teste Auth Service

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-auth-service:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout de c√≥digo
              uses: actions/checkout@v4

            - name: Configurar Python 3.12.4
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.4'

            - name: Install dependencies
              working-directory: ./burguer-app/auth-service
              run: |
                pip install -r requirements.txt

            - name: Rodar testes
              working-directory: ./burguer-app/auth-service
              run: |
                pytest -v --cov=models --cov=services --cov=config --cov=controllers
                radon cc models/user_model.py